# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'WeatherAppProject' do
	pod 'RxSwift', '6.5.0'
	pod 'RxCocoa', '6.5.0'
   	pod 'SnapKit', '~> 5.6.0'
	pod 'Kingfisher', '~> 7.0'

end
