# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewRxPokeProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for NewRxPokeProject
    pod 'RxSwift'
    pod 'RxCocoa'


  target 'NewRxPokeProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewRxPokeProjectUITests' do
    # Pods for testing
  end

end
