# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GithubProject' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GithubProject
    pod 'RxSwift', '6.5.0'
    pod 'RxCocoa', '6.5.0'
    pod 'SnapKit', '~> 5.6.0'

  target 'GithubProjectTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GithubProjectUITests' do
    # Pods for testing
  end

end
